version: '3.9'

services:
  postgres:
    container_name: dungeons_dragon_postgres
    image: postgres:16-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=dd_user
      - POSTGRES_DB=dungeons_dragon
    networks:
      - dndnet
  
  backend:
    container_name: dungeons_dragon_backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=dd_user
      - DB_PASSWORD=S3cret
      - DB_NAME=dungeons_dragon
      - DB_SSLMODE=disable
      - DB_TIMEZONE=Asia/Bangkok
      - JWT_SECRET=mysecretkey
      - FILE_STORAGE_PATH=/app/uploads
      - MAX_FILE_SIZE=10485760
      - DOMAIN=http://localhost:8080
    depends_on:
      - postgres
    networks:
      - dndnet

volumes:
  pgdata:

networks:
  dndnet: